name: Publish devcontainer features

on:
  push:
    branches: [main]
    paths:
      - features/**
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6
      - uses: devcontainers/action@v1
        with:
          publish-features: "true"
          base-path-to-features: features
          generate-docs: "false"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
